<?php

declare(strict_types=1);

namespace App\Publishing\TikTok\Business;

use App\Publishing\Exceptions\PermanentPublishException;
use App\Publishing\TikTok\TikTokTokens;
use Carbon\CarbonImmutable;
use Illuminate\Http\Client\ConnectionException;
use Illuminate\Support\Facades\Http;
use RuntimeException;

/**
 * Authorization for TikTok API for Business (`tt_user`).
 *
 * Same token rhythm as the developer track — a day-long access token, a year-long refresh token —
 * but three things differ and each one fails the call outright:
 *
 * - the authorize URL is generated by TikTok per activated redirect URL, not assembled here;
 * - `redirect_uri` must be sent on every token call and match the app exactly;
 * - the body is JSON, and the response wraps everything in `code`/`message`/`data`.
 *
 * @see https://business-api.tiktok.com/portal/docs/accounts-api-authentication/v1.3
 */
final class TikTokBusinessOAuth implements TikTokTokens
{
    /**
     * Anything the hub needs to carry through authorization goes in `state` as JSON — the redirect
     * URL itself may not hold query parameters.
     */
    public function authorizeUrl(string $state): string
    {
        $url = (string) config('tiktok.business.authorize_url');

        if (blank($url)) {
            throw new RuntimeException('TIKTOK_BUSINESS_AUTHORIZE_URL nije postavljen — TikTok ga generira uz aktivni redirect URL u portalu.');
        }

        // Always show the consent screen: it names the TikTok account being connected, which is
        // the only moment a person can notice it is the wrong brand's.
        return $url.(str_contains($url, '?') ? '&' : '?').http_build_query(['state' => $state, 'disable_auto_auth' => 1]);
    }

    /**
     * @return array{access_token: string, refresh_token: string, open_id: string, expires_at: CarbonImmutable, refresh_expires_at: CarbonImmutable|null, scope: string}
     */
    public function exchangeCode(string $code): array
    {
        return $this->token('tt_user/oauth2/token/', [
            'grant_type' => 'authorization_code',
            'auth_code' => $code,
            'redirect_uri' => $this->redirectUri(),
        ]);
    }

    /**
     * @return array{access_token: string, refresh_token: string, open_id: string, expires_at: CarbonImmutable, refresh_expires_at: CarbonImmutable|null, scope: string}
     */
    public function refresh(string $refreshToken): array
    {
        return $this->token('tt_user/oauth2/refresh_token/', [
            'grant_type' => 'refresh_token',
            'refresh_token' => $refreshToken,
        ]);
    }

    public function revoke(string $accessToken): void
    {
        $this->call('tt_user/oauth2/revoke/', ['access_token' => $accessToken]);
    }

    public function redirectUri(): string
    {
        $configured = (string) config('tiktok.business.redirect');

        return $configured !== '' ? $configured : url('/tiktok/business/callback/');
    }

    /**
     * @param  array<string, string>  $payload
     * @return array{access_token: string, refresh_token: string, open_id: string, expires_at: CarbonImmutable, refresh_expires_at: CarbonImmutable|null, scope: string}
     */
    private function token(string $path, array $payload): array
    {
        $data = $this->call($path, $payload);

        if (blank($data['access_token'] ?? null)) {
            throw new PermanentPublishException('TikTok nije izdao token: '.json_encode($data), 'tiktok_oauth_failed');
        }

        $refreshExpires = (int) ($data['refresh_token_expires_in'] ?? 0);

        return [
            'access_token' => (string) $data['access_token'],
            'refresh_token' => (string) ($data['refresh_token'] ?? ''),
            'open_id' => (string) ($data['open_id'] ?? ''),
            'expires_at' => CarbonImmutable::now()->addSeconds((int) ($data['expires_in'] ?? 86400)),
            'refresh_expires_at' => $refreshExpires > 0 ? CarbonImmutable::now()->addSeconds($refreshExpires) : null,
            'scope' => (string) ($data['scope'] ?? ''),
        ];
    }

    /**
     * @param  array<string, string>  $payload
     * @return array<string, mixed>
     */
    private function call(string $path, array $payload): array
    {
        $this->assertConfigured();

        $url = mb_rtrim((string) config('tiktok.business.api_base'), '/').'/'.mb_ltrim($path, '/');

        try {
            $response = Http::acceptJson()
                ->asJson()
                ->timeout((int) config('tiktok.http_timeout', 30))
                ->post($url, [
                    'client_id' => (string) config('tiktok.business.app_id'),
                    'client_secret' => (string) config('tiktok.business.app_secret'),
                    ...$payload,
                ]);
        } catch (ConnectionException $e) {
            throw new PermanentPublishException("TikTok nije dostupan: {$e->getMessage()}", 'tiktok_unreachable');
        }

        $body = $response->json();

        // A non-zero `code` arrives with HTTP 200, so the status alone never tells you it failed.
        if (! is_array($body) || (int) ($body['code'] ?? -1) !== 0) {
            $message = is_array($body) ? ($body['message'] ?? $response->body()) : $response->body();

            throw new PermanentPublishException('TikTok nije izdao token: '.mb_substr((string) $message, 0, 300), 'tiktok_oauth_failed');
        }

        return (array) ($body['data'] ?? []);
    }

    private function assertConfigured(): void
    {
        foreach (['app_id', 'app_secret'] as $key) {
            if (blank(config("tiktok.business.{$key}"))) {
                throw new RuntimeException('TIKTOK_BUSINESS_'.mb_strtoupper($key).' nije postavljen u .env.');
            }
        }
    }
}
